workflows:
  ios-unsigned-ipa:
    name: iOS Unsigned IPA
    environment:
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.evilcrow.rf2controller"
    working_directory: mobile_app
    scripts:
      - name: Generate missing iOS project files
        script: flutter create --platforms=ios .
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build unsigned iOS app
        script: flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload/
          zip -r ../ipa/EvilCrowRF.ipa Payload
    artifacts:
      - mobile_app/build/ios/ipa/EvilCrowRF.ipa

